Remove numbers from parameters of combined models
SiLeBAT/FSK-Lab pull request #1061
Opened 2022-10-02 20:22 UTC by ahmadswaid

2022-10-10 09:01 UTC, schuelet commented
@ahmadswaid Still testing, looks good so far. I have a question though: how much work would it be to use a color from a predefined list instead of generating a random one? I was thinking, maybe I compile a list for like 10 submodels and the simulator will just pick first one in the list and then moves on to the next as needed. Thus we prevent possibilities of having really aggressive colors that look like something has gone wrong (i.e. bright red).

2022-10-10 10:52 UTC, ahmadswaid commented
@schuelet, No it should not be big issue.
Actually I think we should mix both solutions 
1- take colors from the pre-defined list
2- if this list then is consumed then generate extra non-aggressive colors. 

What do you think?

2022-10-10 11:25 UTC, schuelet commented
@ahmadswaid: I found a joiner bug I missed in pull request #1056. It seems, in a certain edge case there is a null pointer exception when all input parameters are joined AND there are no output parameters in that model. The error is thrown in JoinerNodeUtils -> findSuffix. 
[joiner_issue_no_output_parameters.zip](https://github.com/SiLeBAT/FSK-Lab/files/9745472/joiner_issue_no_output_parameters.zip)

Can you fix that in this PR or should it be done in a separate one?

2022-10-10 11:30 UTC, schuelet commented
> @schuelet, No it should not be big issue. Actually I think we should mix both solutions 1- take colors from the pre-defined list 2- if this list then is consumed then generate extra non-aggressive colors.
> 
> What do you think?

@ahmadswaid : Yes, perfect.
I picked some colors from this website, hopefully they are compatible with our implementation: [https://www.w3schools.com/colors/colors_names.asp](https://www.w3schools.com/colors/colors_names.asp )

[#F0F8FF](https://www.w3schools.com/colors/color_tryit.asp?hex=F0F8FF)
[#F5F5DC](https://www.w3schools.com/colors/color_tryit.asp?hex=F5F5DC)
[#F0FFFF](https://www.w3schools.com/colors/color_tryit.asp?hex=F0FFFF)
[#FFFAF0](https://www.w3schools.com/colors/color_tryit.asp?hex=FFFAF0)
[#FFF8DC](https://www.w3schools.com/colors/color_tryit.asp?hex=FFF8DC)
[#FFE4C4](https://www.w3schools.com/colors/color_tryit.asp?hex=FFE4C4)
[#F0FFF0](https://www.w3schools.com/colors/color_tryit.asp?hex=F0FFF0)
[#E6E6FA](https://www.w3schools.com/colors/color_tryit.asp?hex=E6E6FA)
[#FFF0F5](https://www.w3schools.com/colors/color_tryit.asp?hex=FFF0F5)
[#D3D3D3](https://www.w3schools.com/colors/color_tryit.asp?hex=D3D3D3)
[#AFEEEE](https://www.w3schools.com/colors/color_tryit.asp?hex=AFEEEE)

2022-10-10 11:32 UTC, ahmadswaid commented
> @ahmadswaid: I found a joiner bug I missed in pull request #1056. It seems, in a certain edge case there is a null pointer exception when all input parameters are joined AND there are no output parameters in that model. The error is thrown in JoinerNodeUtils -> findSuffix. [joiner_issue_no_output_parameters.zip](https://github.com/SiLeBAT/FSK-Lab/files/9745472/joiner_issue_no_output_parameters.zip)
> 
> Can you fix that in this PR or should it be done in a separate one?

I'll fix it here! Thanks for investigating.

2022-10-10 19:28 UTC, ahmadswaid commented
@schuelet please have another look.

2022-10-12 13:03 UTC, schuelet requested changes

2022-10-12 13:03 UTC, schuelet commented on de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/joiner/JoinerNodeUtil.java
> +      if(index.get() < COLOR_LIST.length) {
@ahmadswaid: This index variable is used for the parameters, meaning it will increment for each parameter instead of each submodel.

2022-10-12 13:34 UTC, ahmadswaid commented on de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/v2_0/joiner/JoinerNodeUtil.java
> +      if(index.get() < COLOR_LIST.length) {
@schuelet fixed, please review again.

2022-10-12 14:04 UTC, schuelet approved these changes
Looks great, thanks @ahmadswaid !

2022-10-13 07:22 UTC, merged