Feature simulation configurator allows to add file parameters
SiLeBAT/FSK-Lab pull request #1085
Opened 2023-01-14 23:44 UTC by ahmadswaid

Thanks @schuelet for help in preferences tutorial:

`preferences: can be exported when starting KNIME as admin (sudo)
copy preference.epf to /opt/knime/knime_server/workflow_repository/config/client-profiles/executor
replace with executor.epf
add lines to knime.ini (/opt/knime/knime_server/knime_executor/knime.ini):
-profileLocation
http://127.0.0.1:8080/knime/rest/v4/profiles/contents
-profileList
executor`

Anyway, branch tested on my server, @schuelet could you please review this PR!

2023-01-16 12:55 UTC, schuelet requested changes

2023-01-16 12:55 UTC, schuelet commented on de.bund.bfr.knime.js/src/js/app/app.simulation.js
> +						}
@ahmadswaid this piece of code (line 834-842) does not work right now. The parameter values are not shown, regardless Windows or Linux. They are also removed from the simulation when clicking close and apply. Model taken for this is: https://knime.bfr.berlin/landingpage/DB/download/0f454533-c324-43a4-a1d1-5a997125a1ba?status=Any&repository=Any

<img width="783" alt="image" src="https://user-images.githubusercontent.com/38949263/212682298-b4287cfa-8e88-49c5-86c5-5f1012e7155e.png">
<img width="805" alt="image" src="https://user-images.githubusercontent.com/38949263/212682351-a283e442-f307-4170-ba4b-070a01ef3792.png">

2023-01-18 09:09 UTC, schuelet commented
@ahmadswaid Ok, good news, the file parameter values are now visible on local execution. On server execution, the model executes and also takes new files via "add file" upload.
What is still an issue is the UI: On server execution, the button "add file" is still overlapping the file names and on clicking the details of a parameter, the information are pushed down, overlapping with the other parameters. 

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/38949263/213127113-230e0565-a89e-4502-bded-68cdfef317a5.png">

2023-01-18 09:34 UTC, schuelet commented
@ahmadswaid found 2 other issues:
1. When using the Simulation Configurator on Linux and saving a workflow, the portObject can't be opened after the Simulation Configurator (see image below).
2. Adding new files via "add file" button does seem to overwrite all other simulations with those filename values. I added a file called "conso_inputs4.csv" to a new simulation "MyNewSimulation" and yet all simulations have that file now. See json here: 
[simulations_after_adding_new_files.txt](https://github.com/SiLeBAT/FSK-Lab/files/10444263/simulations_after_adding_new_files.txt)

<img width="778" alt="image" src="https://user-images.githubusercontent.com/38949263/213135599-334f381d-699d-4cab-8eb3-9cdb9a1816f3.png">

2023-01-23 13:16 UTC, schuelet commented
@ahmadswaid: Tested the changes and most issues are fixed. Two issues remain:
1. if there are more then one FILE parameters, adding only one leaves the others empty:
<img width="952" alt="image" src="https://user-images.githubusercontent.com/38949263/214048588-30afd827-47e2-483a-a33c-0d328abef5ee.png">

2. the portObject still doesn't load when opening an exported workflow on another computer.

2023-01-24 08:07 UTC, ahmadswaid commented
@schuelet issue No. 1 was solved
work is still in progress on issue No. 2

2023-01-27 10:31 UTC, schuelet commented
@ahmadswaid The portObject Issue seems to be fixed. Unfortunately something broke with the upload, adding files no longer appear in the workspace of the model. I checked the previous commit #42a1c05 and there the upload still worked.

2023-02-13 14:18 UTC, schuelet approved these changes

2023-02-22 11:15 UTC, merged