648 four optional input port for the joiner
SiLeBAT/FSK-Lab pull request #700
Opened 2020-10-12 00:05 UTC by ahmadswaid

Sorry for the huge PR but it can't be divided more.
Steps to be done after approving this PR are written as //TODO task in code.

2020-10-12 12:00 UTC, miguelalba requested changes

2020-10-12 17:23 UTC, ahmadswaid commented on de.bund.bfr.knime.fsklab.nodes/src/de/bund/bfr/knime/fsklab/nodes/NodeUtils.java
> +        return new GenericModel().modelMath(new GenericModelModelMath())
that was only a step in the solution to overcome the errors but to be completed in the metadata joining ticket!

2020-10-12 17:25 UTC, ahmadswaid commented
All test code was already approved and was not written by me, anyway fixed now

2020-10-13 07:45 UTC, miguelalba approved these changes

2020-10-13 08:30 UTC, merged