666 support knime highlighting feature
SiLeBAT/FSK-Lab pull request #706
Opened 2020-10-28 22:52 UTC by ahmadswaid

2020-11-02 16:07 UTC, miguelalba requested changes

2020-11-02 17:06 UTC, ahmadswaid commented on de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v1.9/joiner/joiner.js
> +      editModelsPool('firstModel', selectedModel.modelMath.parameter, selectedModel.generalInformation.name, selectedModel, selectedModel.modelType);
The function is called in other places with arguments of other Object which has another structure.
please look to the call of it with arguments from _joinerModelsData Object

2020-11-02 17:13 UTC, ahmadswaid commented
@miguelalba Unfortunately, I thought if push another commit it will update the PR like with MR in Gitlab.
so I don't know if you noticed that files were labeled with outdated.
I did all the requested changes but don't know if I have to create another PR to have the branch eligible for merging.

2020-11-03 10:57 UTC, miguelalba commented on de.bund.bfr.knime.fsklab.nodes/js-src/de/bund/bfr/knime/fsklab/v1.9/joiner/joiner.js
> +      'markup': `<circle fill="#FF7979"  r="92.5" class="port-body"><title>Parameter ID: ` + param.idmask + `\nParameter Name: ` + param.name + `\nDescription: ` + param.description + `\nUnit: ` + pa
We could use a template string here.

2020-11-03 11:00 UTC, miguelalba approved these changes
It is fine. I would use a template string for the markup in joiner.js:731 but I do not to slow this PR more.

2020-11-03 11:31 UTC, merged