Add conversion algorithm and update endpoint
SiLeBAT/FSK-Lab pull request #715
Opened 2020-11-05 14:24 UTC by miguelalba

This PR includes a metadata conversion algorithm and updates the endpoint in FskService. This commit seems larger than it is. Most of the changes (1900 lines) are from the example JSON metadata for test and a copy of the swagger schema. These two files are needed resources.

The actual changes to check are the algorithm (**ConversionUtils**, ~150 lines) and the **service** (~130). The algorithm is added a small test from a generic model to a process model. More tests can be for other classes if we find annotated models. Regarding the implementation I rewrote it to use the library snakeyaml instead of the Swagger parser since the latter has many implicit dependencies that need to be added to the osgi projects manually. Snakeyaml instead is a single file.

2020-11-06 09:56 UTC, schuelet requested changes
Cant access the endpoint, so I cant validate if the algorithm works.

2020-11-06 09:56 UTC, schuelet commented on de.bund.bfr.knime.fsklab.service/src/de/bund/bfr/knime/fsklab/service/FskService.java
> -  }
remove unused import packages: 
import de.bund.bfr.metadata.swagger.ConsumptionModel;
import de.bund.bfr.metadata.swagger.ConsumptionModelScope;
import de.bund.bfr.metadata.swagger.DataModel;
import de.bund.bfr.metadata.swagger.DataModelGeneralInformation;
import de.bund.bfr.metadata.swagger.DataModelModelMath;
import de.bund.bfr.metadata.swagger.DoseResponseModel;
import de.bund.bfr.metadata.swagger.DoseResponseModelGeneralInformation;
import de.bund.bfr.metadata.swagger.DoseResponseModelModelMath;
import de.bund.bfr.metadata.swagger.DoseResponseModelScope;
import de.bund.bfr.metadata.swagger.ExposureModel;
import de.bund.bfr.metadata.swagger.ExposureModelScope;
import de.bund.bfr.metadata.swagger.GenericModel;
import de.bund.bfr.metadata.swagger.GenericModelDataBackground;
import de.bund.bfr.metadata.swagger.GenericModelGeneralInformation;
import de.bund.bfr.metadata.swagger.GenericModelModelMath;
import de.bund.bfr.metadata.swagger.GenericModelScope;
import de.bund.bfr.metadata.swagger.HealthModel;
import de.bund.bfr.metadata.swagger.HealthModelScope;
import de.bund.bfr.metadata.swagger.Model;
import de.bund.bfr.metadata.swagger.ModelCategory;
import de.bund.bfr.metadata.swagger.OtherModel;
import de.bund.bfr.metadata.swagger.OtherModelDataBackground;
import de.bund.bfr.metadata.swagger.OtherModelGeneralInformation;
import de.bund.bfr.metadata.swagger.OtherModelModelMath;
import de.bund.bfr.metadata.swagger.OtherModelScope;
import de.bund.bfr.metadata.swagger.PredictiveModel;
import de.bund.bfr.metadata.swagger.PredictiveModelDataBackground;
import de.bund.bfr.metadata.swagger.PredictiveModelGeneralInformation;
import de.bund.bfr.metadata.swagger.PredictiveModelModelMath;
import de.bund.bfr.metadata.swagger.PredictiveModelScope;
import de.bund.bfr.metadata.swagger.ProcessModel;
import de.bund.bfr.metadata.swagger.ProcessModelScope;
import de.bund.bfr.metadata.swagger.QraModel;
import de.bund.bfr.metadata.swagger.RiskModel;
import de.bund.bfr.metadata.swagger.ToxicologicalModel;
import de.bund.bfr.metadata.swagger.ToxicologicalModelScope;

2020-11-06 09:56 UTC, schuelet commented on de.bund.bfr.knime.fsklab.service/src/de/bund/bfr/knime/fsklab/service/FskService.java
>      get("convertMetadata/:targetModelClass", (req, res) -> {
should that not be a POST method?

2020-11-10 09:46 UTC, miguelalba commented
Ok. I fixed the conflicts and provided a test. This can be tested and merged to development.

2020-11-10 13:32 UTC, schuelet approved these changes

2020-11-10 14:12 UTC, merged